data: Xac-time_300K_2point_microfios-FeSiB_hac_10Oe_f_10Hz_26-04-24.raw
variables:
    "signal": Signal (mV)
    "drive":  Drive (Oe)
    "frequency": Frequency (Hz)
    "bin": Bin
    "images": FALSE
